import time

def wakeup():
    print("Zz...")
    time.sleep(1.5)
    print("...zZz")
    time.sleep(1.5)
    print("........")
    time.sleep(2)
    print("  z  |\__/| z                             ")
    print(" Z  /_  _ |        Waking up Calicobot... ")
    print("    \_^_   \  z                           ")
    print("  z  /CALICO\                             ")
    time.sleep(5)
    print("...")
    time.sleep(1.5)
    print(".....")
    time.sleep(1.5)
    print("........")
    time.sleep(1.5)
    print("..........!")
    time.sleep(2)
    print("  +  |\__/| +                             ")
    print(" x  /.  . |        Calicobot is awake!    ")
    print("    \_^_   \  x                           ")
    print("  +  /CALICO\                             ")
    time.sleep(4)
    print("Who are you?")
    time.sleep(2)
    print("Why are you waking me up?")
    time.sleep(2)
    print("Tell me your name.")

def byebye():
    print("Oh.")
    time.sleep(1.5)
    print("Okay!")
    time.sleep(2)
    print("I'll just go back to sleep then.")
    time.sleep(2)
    print("I hope you'll visit me again someday!")
    time.sleep(3)
    print("  z  |\__/| z                             ")
    print(" Z  /_  _ |      Calicobot is going back  ")
    print("    \_^_   \  z  to sleep...              ")
    print("  z  /CALICO\                             ")
    time.sleep(5)
    print("Calicobot has fallen asleep.")
    time.sleep(2.5)
    print("Thanks for playing with Calicobot! See you!")
    print("  *  |\__/| *  ")
    print(" *  /^  ^ |    ")
    print("    \_^_   \ * ")
    print("  *  /CALICO\  ")

def positive_answer():
    print("Yay! I'm excited!")
    time.sleep(1.5)
    print("Okay, so I'm still a very puny little bot.")
    time.sleep(2)
    print("But I have so much more room for growth!")
    time.sleep(2)
    print("  *  |\__/| *  ")
    print(" *  /^  ^ |    ")
    print("    \_^_   \ * ")
    print("  *  /CALICO\  ")
    time.sleep(2.5)
    print("Let me think of things we can do...")
    time.sleep(4)
